
USER_PAGE_SIZE = 500
TASK_PAGE_SIZE = 999
STATUS = {'static': 'SUCCESS,FAILED,CANCELED', 'dynamic': 'PENDING,IN_PROGRESS'}
TASK_STATUS = STATUS['static'] + STATUS['dynamic']
STATUS_LIST = {'static': ['SUCCESS','FAILED','CANCELED'], 'dynamic': ['PENDING','IN_PROGRESS']}
TASK_STATUS_LIST = STATUS_LIST['static'] + STATUS_LIST['dynamic']